---
- name: Instalación Zabbix 7.0
  hosts: zabbix
  become: yes
  vars:
    # Variables para la base de datos
    db_host: "192.168.1.12"
    db_name: "zabbix"
    db_user: "zabbix"
    db_password: "Huawei12#$"
    # Variables para PHP timezone
    php_timezone: "America/Bogota"  # Ajusta según tu zona horaria

  tasks:
    - name: Descargar repositorio Zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu24.04_all.deb
        dest: /tmp/zabbix.deb

    - name: Instalar repositorio Zabbix
      apt:
        deb: /tmp/zabbix.deb
        
    - name: Actualizar repositorios
      apt:
        update_cache: yes
        
    - name: Instalar componentes Zabbix
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Configurar archivo zabbix_server.conf
      template:
        src: templates/zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
        owner: zabbix
        group: zabbix
        mode: '0640'
      notify: restart zabbix-server

    - name: Configurar PHP timezone
      lineinfile:
        path: /etc/zabbix/apache.conf
        regexp: '^.*php_value date.timezone.*'
        line: "        php_value date.timezone {{ php_timezone }}"
      notify: restart apache2

    - name: Importar esquema inicial de base de datos
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
      delegate_to: "{{ db_host }}"
      run_once: true

    - name: Iniciar y habilitar servicios
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted
