---
- name: Instalación Zabbix 7.0
  hosts: zabbix
  become: yes
  vars:
    # Variables para la base de datos
    db_host: "192.168.30.5"
    db_name: "zabbix"
    db_user: "root"
    db_password: "Huawei12#$"
    # Variables para PHP timezone
    php_timezone: "America/Bogota"

  tasks:
    - name: Descargar repositorio Zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu24.04_all.deb
        dest: /tmp/zabbix.deb

    - name: Instalar repositorio Zabbix
      apt:
        deb: /tmp/zabbix.deb
        
    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar el paquete de localización
      apt:
        name: locales
        state: present
        update_cache: yes

    - name: Generar el locale en_US.UTF-8
      command: locale-gen en_US.UTF-8

    - name: Configurar el locale por defecto en el sistema
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'
        create: yes

    - name: Actualizar los locales
      command: update-locale LANG=en_US.UTF-8
        
    - name: Instalar componentes Zabbix
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Configurar archivo zabbix_server.conf
      copy:
        content: |
          DBHost={{ db_host }}
          DBName={{ db_name }}
          DBUser={{ db_user }}
          DBPassword={{ db_password }}
          
          LogFile=/var/log/zabbix/zabbix_server.log
          PidFile=/run/zabbix/zabbix_server.pid
          SocketDir=/run/zabbix
          
          LogFileSize=0
          Timeout=4
          AlertScriptsPath=/usr/lib/zabbix/alertscripts
          ExternalScripts=/usr/lib/zabbix/externalscripts
          FpingLocation=/usr/bin/fping
          Fping6Location=/usr/bin/fping6
          LogSlowQueries=3000
          StatsAllowedIP=127.0.0.1
        dest: /etc/zabbix/zabbix_server.conf
        owner: zabbix
        group: zabbix
        mode: '0640'
      notify: restart zabbix-server

    - name: Configurar PHP timezone
      lineinfile:
        path: /etc/zabbix/apache.conf
        regexp: '^.*php_value date.timezone.*'
        line: "        php_value date.timezone {{ php_timezone }}"
      notify: restart apache2

    - name: Obtener archivo SQL del servidor Zabbix
      slurp:
        src: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
      register: sql_file_content
      delegate_to: 192.168.30.2  # o el servidor Zabbix específico

    - name: Copiar archivo SQL al servidor de base de datos
      copy:
        content: "{{ sql_file_content['content'] | b64decode }}"
        dest: /tmp/server.sql.gz
      delegate_to: "{{ db_host }}"

    - name: Descomprimir archivo SQL
      shell: |
        gunzip -f /tmp/server.sql.gz
      delegate_to: "{{ db_host }}"

    - name: Importar esquema inicial de base de datos
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /tmp/server.sql
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
      delegate_to: "{{ db_host }}"
      run_once: true

    - name: Iniciar y habilitar servicios
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted

