---
- name: Instalación Zabbix 7.0
  hosts: zabbix
  become: yes
  vars:
    # Variables para la base de datos
    db_host: "192.168.1.12"
    db_name: "zabbix"
    db_user: "zabbix"
    db_password: "Huawei12#$"
    # Variables para PHP timezone
    php_timezone: "America/Bogota"

  tasks:
    - name: Descargar repositorio Zabbix
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu24.04_all.deb"
        dest: /tmp/zabbix.deb
        mode: '0644'
      register: zabbix_repo_download
      retries: 3
      delay: 5
      until: zabbix_repo_download is succeeded

    - name: Verificar que el archivo Zabbix se descargó correctamente
      stat:
        path: /tmp/zabbix.deb
      register: zabbix_deb_file

    - name: Fallar si el archivo de Zabbix no existe o es muy pequeño
      fail:
        msg: "El archivo zabbix.deb no se descargó correctamente o está incompleto"
      when: not zabbix_deb_file.stat.exists or zabbix_deb_file.stat.size < 1000

    - name: Instalar repositorio Zabbix
      apt:
        deb: /tmp/zabbix.deb

    - name: Actualizar repositorios
      apt:
        update_cache: yes

    - name: Instalar componentes Zabbix
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    # Crear directorio de plantillas localmente en el controlador de Ansible
    - name: Crear directorio de plantillas localmente
      local_action:
        module: file
        path: "./templates"
        state: directory
        mode: '0755'

    # Crear archivo de plantilla zabbix_server.conf.j2 en el controlador de Ansible
    - name: Crear archivo de plantilla zabbix_server.conf.j2
      local_action:
        module: copy
        dest: "./templates/zabbix_server.conf.j2"
        content: |
          # Archivo de configuración de Zabbix
          DBHost={{ db_host }}
          DBName={{ db_name }}
          DBUser={{ db_user }}
          DBPassword={{ db_password }}
        mode: '0644'

    # Copiar archivo de configuración zabbix_server.conf al servidor gestionado
    - name: Configurar archivo zabbix_server.conf
      template:
        src: "./templates/zabbix_server.conf.j2"
        dest: /etc/zabbix/zabbix_server.conf
        owner: zabbix
        group: zabbix
        mode: '0640'
      notify: restart zabbix-server

    - name: Configurar PHP timezone en apache.conf de Zabbix
      lineinfile:
        path: /etc/zabbix/apache.conf
        regexp: '^.*php_value date.timezone.*'
        line: "        php_value date.timezone {{ php_timezone }}"
      notify: restart apache2

    - name: Crear base de datos Zabbix
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_host: "{{ db_host }}"
        login_user: root
        login_password: "{{ db_password }}"
      delegate_to: localhost
      run_once: true

    - name: Importar esquema inicial de base de datos
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
      delegate_to: localhost
      run_once: true

    - name: Iniciar y habilitar servicios
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

  handlers:
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted
